# -*-python-*-

Import( "env" )

py_dir = '../../fractalysis/engine'

# Build wrappers as shared libraries
lib_env=env.Copy()

sources= lib_env.ALEAGlob( '*.cpp' )
target= "_bcmcompute"

lib_env.AppendUnique(LIBS= ['pgltool','pglmath','pglsg', 'pglgui3', 'pglalgo'])
lib_env.ALEAWrapper( py_dir, target, sources )


