# -*-python-*-

Import( "env" )

py_dir = '../../fractalysis/engine'

# Build wrappers as shared libraries
env1=env.Copy()

sources= ["bcmCompute_wrapper.cpp"]
target= "_bcmcompute"

env1.AppendUnique(LIBS= ['engine','pgltool','pglmath','pglsg', 'pglgui3', 'pglalgo'])
env1.ALEAWrapper( py_dir, target, sources )


