{% set version = "2.0.0" %}

package:
  name: openalea.fractalysis
  version: {{ version }}

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install --prefix=$PREFIX

requirements:
  build:
    - python
    - openalea.deploy #==2.0.0
    - openalea.sconsx
    - boost
    - qt <5
    - openalea.plantgl
  run:
    - boost
    - openalea.plantgl
    - qt <5

test:
  imports:
    - openalea.fractalysis
    - openalea.fractalysis.engine

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill v2 License
  summary: 3D Fractal analysis package
