# -*-python-*-
#import os, re

Import( "env" )

lib_env= env.Clone()

includes= lib_env.ALEAGlob('*.h')
lib_env.ALEAIncludes( "fractalysis/engine", includes )

sources = lib_env.ALEAGlob('*.cpp')

# Add defines to export symbols on Windows
DEFINES= list(env['CPPDEFINES'])
DEFINES.append('BCM_MAKEDLL')

# Link with the following libraries
LIBRARIES= list(lib_env['LIBS'])
LIBRARIES.extend(['pgltool','pglmath','pglsg', 'pglgui', 'pglalgo']) #with qt3, pglgui3 instead of pglgui

lib_env.ALEALibrary( "engine",
                     sources,
                     CPPDEFINES = DEFINES,
                     LIBS = LIBRARIES )

