
# This file has been generated at Thu Jun 12 11:00:51 2008

from openalea.core import *


__name__ = 'Demo.Light'

__editable__ = True
__version__ = '0.1'
__description__ = 'Multi-scale light interception demo'
__license__ = 'CeCIL'
__authors__ = 'DDS'
__url__ = ''
__institutes__ = 'VirtualPlants'
__icon__ = ''
 

__all__ = ['_143835372', 'MuSLIM', 'scalesTable']


_143835372 = DataFactory(name='mango_f21_L.bgeom', 
                    description='Mango f21', 
                    editors=None,
                    includes=None,
                    )



MuSLIM = CompositeNodeFactory(name='MuSLIM', 
                             description='Generates MuSLIM images', 
                             category='Light',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('catalog.pickle', 'pickle load'),
   3: ('Demo.Light', 'scalesTable'),
   4: ('Geometric Operator', 'import scene'),
   5: ('PlantGL.Objects', 'Scene'),
   6: ('fractalysis.light', 'create MSS'),
   7: ('catalog.data', 'string'),
   8: ('fractalysis.light', 'generatePix'),
   10: ('fractalysis.light', 'Light direction'),
   11: ('Demo.Light', 'mango_a19_L.bgeom'),
   14: ('PlantGL.Visualization', 'plot3D'),
   15: ('system', 'annotation'),
   16: ('system', 'annotation'),
   17: ('system', 'annotation'),
   18: ('system', 'annotation'),
   19: ('system', 'annotation'),
   20: ('system', 'annotation'),
   21: ('system', 'annotation'),
   22: ('system', 'annotation'),
   23: ('system', 'annotation'),
   24: ('system', 'annotation'),
   25: ('system', 'annotation'),
   26: ('system', 'annotation'),
   28: ('image.basics', 'view image'),
   29: ('catalog.file', 'packagedir')},
                             elt_connections={  135712536: (4, 0, 5, 0),
   135712548: (2, 0, 6, 2),
   135712560: (29, 0, 8, 4),
   135712572: (6, 0, 8, 0),
   135712584: (11, 0, 4, 0),
   135712596: (3, 0, 2, 0),
   135712620: (8, 0, 28, 0),
   135712632: (5, 0, 6, 1),
   135712644: (7, 0, 6, 0),
   135712656: (10, 0, 8, 1),
   135712668: (5, 0, 14, 0)},
                             elt_data={  2: {  'caption': 'pickle load',
         'hide': True,
         'lazy': False,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 466.25,
         'posy': 278.75,
         'priority': 0,
         'user_application': None},
   3: {  'caption': 'scalesTable',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([2]),
         'posx': 668.75,
         'posy': 130.0,
         'priority': 0,
         'user_application': None},
   4: {  'caption': 'import scene',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 228.75,
         'posy': 216.25,
         'priority': 0,
         'user_application': None},
   5: {  'caption': 'Scene',
         'hide': True,
         'lazy': False,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 335.0,
         'posy': 277.5,
         'priority': 0,
         'user_application': None},
   6: {  'caption': 'create MSS',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 348.75,
         'posy': 408.75,
         'priority': 0,
         'user_application': None},
   7: {  'caption': "'mango_a19'",
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 113.75,
         'posy': 418.75,
         'priority': 0,
         'user_application': None},
   8: {  'caption': 'generatePix',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([5]),
         'posx': 321.25,
         'posy': 630.0,
         'priority': 0,
         'user_application': None},
   10: {  'caption': 'Light direction',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 428.75,
          'posy': 505.0,
          'priority': 0,
          'user_application': None},
   11: {  'caption': 'mango_a19_L.bgeom',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([2]),
          'posx': 297.5,
          'posy': 111.25,
          'priority': 0,
          'user_application': None},
   14: {  'caption': 'plot3D',
          'hide': True,
          'lazy': False,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 125.0,
          'posy': 321.25,
          'priority': 0,
          'user_application': None},
   15: {'posx': -8.741639333367857, 'posy': 233.39966151849652, 'txt': ''},
   16: {'posx': 583.75, 'posy': 270.0, 'txt': ''},
   17: {'posx': 485.0, 'posy': 413.75, 'txt': ''},
   18: {'posx': 588.75, 'posy': 502.5, 'txt': ''},
   19: {'posx': 648.75, 'posy': 571.25, 'txt': ''},
   20: {'posx': 92.5, 'posy': 530.0, 'txt': ''},
   21: {'posx': 83.75, 'posy': 738.75, 'txt': ''},
   22: {'posx': 493.34710743801656, 'posy': 84.795684113865946, 'txt': ''},
   23: {'posx': 493.34710743801656, 'posy': 122.29568411386589, 'txt': ''},
   24: {'posx': 528.34710743801656, 'posy': 152.29568411386589, 'txt': ''},
   25: {'posx': 490.84710743801656, 'posy': 44.795684113865946, 'txt': ''},
   26: {'posx': 17.5, 'posy': 51.25, 'txt': ''},
   28: {  'caption': 'view image',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 320.0,
          'posy': 740.0,
          'priority': 0,
          'user_application': None},
   29: {  'caption': 'packagedir',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 618.75,
          'posy': 578.75,
          'priority': 0,
          'user_application': None},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set([]),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set([]),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0}},
                             elt_value={  2: [],
   3: [(0, 'PackageData(Demo.Light, scalesTable)'), (1, 'None'), (2, 'None')],
   4: [],
   5: [],
   6: [(3, "'Cvx Hull'")],
   7: [(0, "'mango_a19'")],
   8: [(2, "['A', 'A', 'R']"), (3, "'100x100'")],
   10: [(0, '10'), (1, '52.619999999999997')],
   11: [  (0, 'PackageData(Demo.Light, mango_a19_L.bgeom)'),
          (1, 'None'),
          (2, 'None')],
   14: [],
   15: [],
   16: [],
   17: [],
   18: [],
   19: [],
   20: [],
   21: [],
   22: [],
   23: [],
   24: [],
   25: [],
   26: [],
   28: [],
   29: [(0, "'Demo.Light'")],
   '__in__': [],
   '__out__': []},
                             lazy=True,
                             )



scalesTable = DataFactory(name='scalesTable', 
                    description='Mango f21 scales description', 
                    editors=None,
                    includes=None,
                    )



